infer_eye_blink_ref_frames_start_idx: 40 # start index of the ref blink sequence in the GT dataset
infer_eye_blink_ref_frames_end_idx: 100  # end index of the ref blink sequence in the GT dataset
infer_sil_ref_frame_idx: 7780 # index of the ref frame with a closed mouth in the GT dataset